version: '2'
services:

    redis:
        image: 'redis:3.2.7'
        # command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow


    webserver:
        image: airflow:latest
        restart: always
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
#            - POSTGRES_USER=airflow
#            - POSTGRES_PASSWORD=airflow123
#            - POSTGRES_HOST=cbattista-airflow.cinw9err8rha.us-east-1.rds.amazonaws.com
#            - POSTGRES_DB=airflow
#            - SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow123@cbattista-airflow.cinw9err8rha.us-east-1.rds.amazonaws.com/airflow
#            - CELERY__CELERY_RESULT_BACKEND = db+postgresql://airflow:airflow123@cbattista-airflow.cinw9err8rha.us-east-1.rds.amazonaws.com/airflow?connect_timeout=60
            #- REDIS_PASSWORD=redispass
        volumes:
            - /usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
#        healthcheck:
#            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
#            interval: 30s
#            timeout: 30s
#            retries: 3

    flower:
        image: puckel/docker-airflow:1.9.0-3
        depends_on:
            - redis
        restart: always
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
#            - POSTGRES_HOST=cbattista-airflow.cinw9err8rha.us-east-1.rds.amazonaws.com
#            - POSTGRES_USER=airflow
#            - POSTGRES_PASSWORD=airflow123
#            - POSTGRES_DB=airflow

        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: airflow:latest
        restart: always
        depends_on:
            - webserver
        volumes:
            # add the
            - /usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
#            - POSTGRES_HOST=cbattista-airflow.cinw9err8rha.us-east-1.rds.amazonaws.com
#            - POSTGRES_USER=airflow
#            - POSTGRES_PASSWORD=airflow123
#            - POSTGRES_DB=airflow
#            - SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow123@cbattista-airflow.cinw9err8rha.us-east-1.rds.amazonaws.com/airflow
#            - CELERY__CELERY_RESULT_BACKEND = db+postgresql://airflow:airflow123@cbattista-airflow.cinw9err8rha.us-east-1.rds.amazonaws.com/airflow?connect_timeout=60

            # - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        image: airflow:latest
        restart: always
        depends_on:
            - scheduler
        volumes:
            - /usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
#            - POSTGRES_HOST=cbattista-airflow.cinw9err8rha.us-east-1.rds.amazonaws.com
#            - POSTGRES_USER=airflow
#            - POSTGRES_PASSWORD=airflow123
#            - POSTGRES_DB=airflow
#            - SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow123@cbattista-airflow.cinw9err8rha.us-east-1.rds.amazonaws.com/airflow
#            - CELERY__CELERY_RESULT_BACKEND = db+postgresql://airflow:airflow123@cbattista-airflow.cinw9err8rha.us-east-1.rds.amazonaws.com/airflow?connect_timeout=60

            #- REDIS_PASSWORD=redispass
        command: worker
