---
template_path: templates/airflow-alarms.yaml
stack_name: airflow-etl-prod-airflow-alarms

parameters:
  workerService: !stack_output airflow-cluster::workerService
  webserverService: !stack_output airflow-cluster::webserverService
  schedulerService: !stack_output airflow-cluster::schedulerService
  notificationEmailAddress: christian.battista@tophatmonocle.com
