---
template_path: templates/airflow-metadata.yaml
stack_name: airflow-etl-prod-airflow-metadata

parameters:
  PostgresUser: airflow
  PostgresPW: B8hAhY7wTCLwL6wC
  PostgresDB: airflow
  VpcID: vpc-b22a68d4
  Subnet1: subnet-6cf6d437
  Subnet2: subnet-ac9bfe90
  Subnet3: subnet-c507e08d
  Subnet4: subnet-4bae9966
  Subnet5: subnet-c43d39c8

