---
template_path: templates/cluster-infrastructure.yaml
parameters:
  PostgresHost: cbattista-airflow.cinw9err8rha.us-east-1.rds.amazonaws.com
  PostgresUser: airflow
  PostgresPW: airflow123
  PostgresDB: airflow

