template_path: templates/cluster_infrastructure.yml

#TODO - How to get these params from SSM?

parameters:
  PostgresHost: cbattista-airflow.cinw9err8rha.us-east-1.rds.amazonaws.com
  PostgresUser: airflow
  PostgresPW: airflow123
  PostgresDB: airflow