---
template_path: templates/cluster-infrastructure.yaml
dependencies: airflow-persistent-data
name: airflow-cluster
parameters:
  PostgresHost: !stack_output_external airflow-persistent-data::metadataDBAddress
  PostgresUser: airflow
  PostgresPW: airflow123
  PostgresDB: airflow
  RedisHost: !stack_output_external airflow-persistent-data::eventQueueAddress

  VpcID: vpc-d92765bf
  SecurityGroup: sg-71773f39
