---
template_path: templates/persistent-data-infrastructure.yaml

stack_name: airflow-persistent-data

parameters:
  # TODO - get these params from SSM
  PostgresUser: airflow
  PostgresPW: airflow123
  PostgresDB: airflow
  VpcID: vpc-d92765bf
  SecurityGroup: sg-71773f39
