---
Description: Airflow resources that persist between cluster deploys - e.g., metadata DB, Queue, and log bucket.

Parameters:
  SecurityGroup:
    Type: String
  PostgresUser:
    Type: String
  PostgresPW:
    Type: String
  VpcID:
    Type: String
  PostgresDB:
    Type: String
  Subnet1:
      Type: String
  Subnet2:
    Type: String
  Subnet3:
    Type: String
  Subnet4:
    Type: String
  Subnet5:
    Type: String


Resources:

  # securityGroup: TODO - make the security group here ?
  #  Type: "AWS::EC2:SecurityGroup"
  #  Properties:

  # TODO - create the subnet group for RDS and Elasticache
  securityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription:  For the Airflow ETL Cluster
      VpcId: !Ref VpcID

  logBucket:
      Type: "AWS::S3::Bucket"

  logBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref logBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::008963853103:role/Administrator' # TODO - use SSM to provide this
            Action: 's3:*'
            Resource: !Sub 'arn:aws:s3:::${logBucket}'
          - Effect: Allow
            Principal: '*'
            Action: 's3:*'
            Resource: !Sub 'arn:aws:s3:::${logBucket}'
            Condition:
              StringEquals:
                'aws:SourceVpc': vpc-d92765bf

  dbSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: For Airflow Metadata DB
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2
        - !Ref Subnet3
        - !Ref Subnet4
        - !Ref Subnet5


  metaDataDB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 20
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro
      DBName: !Ref PostgresDB
      DBSubnetGroupName: !Ref dbSubnetGroup
      Engine: postgres
      MasterUsername: !Ref PostgresUser
      MasterUserPassword: !Ref PostgresPW
      PubliclyAccessible: False
      VPCSecurityGroups:
        - !Ref SecurityGroup

  queueSubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties:
      Description: For Airflow Event Queue
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2
        - !Ref Subnet3
        - !Ref Subnet4
        - !Ref Subnet5

  eventQueue:
    Type: "AWS::ElastiCache::CacheCluster"
    Properties:
      CacheNodeType: cache.t2.micro
      CacheSubnetGroupName: !Ref queueSubnetGroup
      Engine: redis
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - !Ref SecurityGroup

Outputs:
  metadataDBAddress:
    Value: !GetAtt metaDataDB.Endpoint.Address

  metadataDBPost:
    Value: !GetAtt metaDataDB.Endpoint.Port

  eventQueueAddress:
    Value: !GetAtt eventQueue.RedisEndpoint.Address

  eventQueuePort:
    Value: !GetAtt eventQueue.RedisEndpoint.Port
