---
Description: Airflow resources that persist between cluster deploys - e.g., metadata DB, Queue, and log bucket.

Resources:
  containerRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: airflow

Outputs:
  repositoryName:
    Value: !Ref containerRepository
