---
Description: Alarms for Airflow Cluster

Parameters:
  webserverService:
    Type: String
  workerService:
    Type: String
  schedulerService:
    Type: String
  notificationEmailAddress:
    Type: String

Resources:
  workerMemoryAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmActions:
        - !Ref criticalAlertTopic
      OKActions:
        - !Ref criticalAlertTopic
      MetricName: MemoryUtilization
      NameSpace: AWS/ECS
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: 90
      ComparisonOperation: GreatThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref workerService

  workerCpuAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:

      AlarmActions:
        - !Ref criticalAlertTopic
      OKActions:
        - !Ref criticalAlertTopic
      MetricName: CPUUtilization
      NameSpace: AWS/ECS
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: 90
      ComparisonOperation: GreatThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref workerService

  schedulerMemoryAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmActions:
        - !Ref criticalAlertTopic
      OKActions:
        - !Ref criticalAlertTopic
      MetricName: MemoryUtilization
      NameSpace: AWS/ECS
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: 90
      ComparisonOperation: GreatThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref schedulerService

  schedulerCpuAlarm:
    Type: "AWS::CloudWatch::Alarm"

    Properties:
      AlarmActions:
        - !Ref criticalAlertTopic
      OKActions:
        - !Ref criticalAlertTopic
      MetricName: CPUUtilization
      NameSpace: AWS/ECS
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: 90
      ComparisonOperation: GreatThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref schedulerService

  webserverAlarm:
    Type: "AWS::CloudWatch::Alarm"

    Properties:
      AlarmActions:
        -!Ref criticalAlertTopic
      OKActions:
        -!Ref criticalAlertTopic
      MetricName: UnHealthyHostCount
      NameSpace: AWS/ELB
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 3
      Threhold: 1

  criticalAlertTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        - Endpoint: !Ref notificationEmailAddress
          Protocol: email
