---
Description: Airflow resources that persist between cluster deploys - e.g., metadata DB, Queue, and log bucket.

Resources:
  logBucket:
      Type: "AWS::S3::Bucket"

    logBucketPolicy:
      Type: "AWS::S3::BucketPolicy"
      Properties:
        Bucket: !Ref logBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                AWS: 'arn:aws:iam::008963853103:role/Administrator' # TODO - use SSM to provide this
              Action: 's3:*'
              Resource: !Sub 'arn:aws:s3:::${logBucket}'
            - Effect: Allow
              Principal: '*'
              Action: 's3:*'
              Resource: !Sub 'arn:aws:s3:::${logBucket}'
              Condition:
                StringEquals:
                  'aws:SourceVpc': vpc-d92765bf

  # TODO - Add REDIS
  # TODO - Add POSTGRES
